apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-locker
  labels:
    app: api-locker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-locker
  template:
    metadata:
      labels:
        app: api-locker
    spec:
      nodeSelector:
        persistent: "yes"
      containers:
        - name: api-locker
          image: softlynx/locker:1.1
          args: []
          envFrom:
            - secretRef:
                name: locker-api-key
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: api-locker
  annotations:
spec:
  type: ClusterIP
  selector:
    app: api-locker
  ports:
    - protocol: TCP
      port: 8443
      name: grpc
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: api-locker
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`locker.api.softlynx.ru`)
      kind: Rule
      services:
        - name: api-locker
          port: 8443
          scheme: https
#  tls:


